// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbbarkslztgthdueblkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYmFya3NsenRndGhkdWVibGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzc2OTYsImV4cCI6MjA2MjcxMzY5Nn0.KyiDC4Zk1i-JgKkh5-Y2HKYG6yDEHvzlYrighkO7dpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);