// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxfdqrussltcibptiltm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZmRxcnVzc2x0Y2licHRpbHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDE1NjUsImV4cCI6MjA1OTUxNzU2NX0.aJbVEWeoKnzIUiafuhHvTyGznae7B-YnFCznc6ZU3G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);